# Generated by Django 5.2.4 on 2025-07-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pedido_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritado_por', to='core.produto'),
        ),
    ]
