# Generated by Django 5.2.4 on 2025-07-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario_favoritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='enderecousuario',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enderecousuario',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='enderecousuario',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enderecousuario',
            name='estado',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='enderecousuario',
            name='logradouro',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='enderecousuario',
            name='numero',
            field=models.CharField(max_length=20),
        ),
    ]
