# Generated by Django 5.2.4 on 2025-07-31 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pedido_endereco_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecousuario',
            name='cep',
            field=models.CharField(help_text='Formato 00000-000', max_length=9),
        ),
        migrations.AlterField(
            model_name='enderecousuario',
            name='estado',
            field=models.CharField(help_text='Sigla do estado, ex: SP', max_length=2),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(default='Pendente', help_text='Status atual do pedido.', max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(help_text='Descrição detalhada do produto.'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem do produto.', null=True, upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(help_text='Marca do produto (ex: Risqué).', max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(help_text='Nome do produto.', max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, help_text='Preço de venda do produto.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(help_text='CPF do usuário, deve ser único.', max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone de contato do usuário.', max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cartao', models.CharField(help_text='Ex: 1234 5678 1234 5678', max_length=19)),
                ('nome_titular', models.CharField(max_length=255)),
                ('data_validade', models.CharField(help_text='MM/AA', max_length=5)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
